export type ProjectSlug = "atlas" | "sentinel" | "aegis" | "hermes" | "prism";

const platform = "Security intelligence platform";
const applied = "Applied ML & evaluation";

export const projects = [
  {
    slug: "atlas", name: "Atlas Graph", accent: "cyan", category: "Knowledge graph · Data engineering", endpoint: "graph", logic: "lib/platform.ts", group: platform,
    tagline: "Trusted entities and attack paths",
    context: "Security tools disagree about the same laptop. Trace every path to critical data, then remove one.",
    summary: "Resolve fragmented security records, calculate attack paths, and test which remediation removes the most risk.",
    intro: "Five fragmented security sources become one traceable graph. Explore every path from an external entry point to critical data, then test which control removes the most risk.",
    tags: ["Graph traversal", "Entity resolution", "Lineage", "What-if analysis"],
    facts: ["5 synthetic sources", "Attack-path search", "What-if remediation"],
    problem: "Security tools describe the same users, devices, services, and findings with different identifiers. Without trustworthy identity and relationships, downstream analytics produce duplicate alerts and misleading attack paths.",
    approach: "Compare source records field by field to link them into canonical entities with lineage, build a directed security graph, and enumerate every path from an exposed entry point to each critical data store. Every edge carries a relationship, an assumed likelihood, and the control that would remove it.",
    baseline: "The baseline graph uses exact identifiers and all observed edges. The enhanced pipeline links noisy records with weighted field comparisons, routes borderline pairs to review, and preserves the evidence behind each canonical entity.",
    measurement: "The live API reports reachable critical paths, the top path score, paths removed by each remediation, source coverage, and field-level match evidence. Path score is the product of edge likelihoods: a heuristic for ranking, not a probability of compromise.",
    failure: "Missing telemetry can hide edges, stale access data can create paths that no longer exist, and correlated edge assumptions make multiplicative scores optimistic. Match weights are hand-set here and must be learned and calibrated on reviewed pairs before production use.",
    production: "Process source snapshots with Spark, store the versioned graph in a graph database, learn entity-resolution weights from reviewed pairs, enforce field-level lineage, and validate proposed attack paths with asset owners before driving remediation.",
  },
  {
    slug: "sentinel", name: "Sentinel ModelOps", accent: "lime", category: "Machine learning · MLOps", endpoint: "monitor", logic: "lib/platform.ts", group: platform,
    tagline: "Fitted classifier, drift, and explanations",
    context: "A model can look accurate until live traffic shifts. Compare it with a simpler baseline.",
    summary: "Compare, explain, and stress-test a fitted intrusion classifier under population drift and different decision thresholds.",
    intro: "A fitted intrusion classifier, not a hand-written score. Compare the champion against its baseline, tune the operating threshold, introduce drift, and explain an individual prediction.",
    tags: ["Logistic regression", "Champion vs baseline", "PSI drift", "Local explanations"],
    facts: ["1,400 train · 600 test rows", "Champion vs baseline", "Drift & explanations"],
    problem: "A classifier can look strong at a default threshold while producing unacceptable false positives, failing on shifted traffic, or hiding which inputs drive individual decisions.",
    approach: "Fit two L2-regularized logistic models on a reproducible public-safe benchmark inspired by the UNSW-NB15 feature domain. Compare a two-feature baseline with a six-feature champion, then rescore a fixed test population under controlled covariate shift.",
    baseline: "The baseline is trained with two traffic features; the champion uses all six. Both are evaluated on the same 600 labeled samples, with the same threshold and drift controls, so the comparison is reproducible.",
    measurement: "Precision, recall, F1, false-positive rate, confusion counts, PSI, score distributions, fitted weights, and per-example logit contributions are calculated by the live endpoint. The source rows are generated and synthetic; results are not claims about the official UNSW-NB15 benchmark.",
    failure: "Synthetic features simplify real network behavior, PSI is sensitive to binning, and covariate drift does not necessarily imply quality loss. Linear contributions explain this model's output; they are not causal effects.",
    production: "Train on licensed source data with a temporal split, add calibration and attack-family slice metrics, log artifacts and data versions in MLflow, monitor delayed labels, and define champion–challenger rollback criteria.",
  },
  {
    slug: "aegis", name: "Aegis Investigator", accent: "violet", category: "Agentic AI · Tool use · Guardrails · Evals", endpoint: "agent", logic: "lib/aegis-agent.ts", group: platform,
    tagline: "LLM agent, policy gate, and a scored eval",
    context: "Evidence sits in five systems, and one of them is written by the attacker. Investigate, cite, and wait for approval.",
    summary: "An LLM agent plans its own tool calls, retrieves a procedure with the Prism retriever, and cites every finding. A deterministic policy gate and a human must clear anything it proposes.",
    intro: "A real tool-using LLM agent on GPT-5.4-mini. It chooses which of five read-only tools to call, searches procedures through the Prism BM25 + dense retriever, and returns a structured, cited conclusion. It can only propose: a deterministic policy gate checks the proposal against the evidence from the same run, and nothing executes until a human approves.",
    tags: ["LLM tool calling", "Structured outputs", "Prompt-injection defense", "Agent evals"],
    facts: ["5 read-only tools", "Scored eval vs baseline", "Policy gate + human approval"],
    problem: "Incident evidence is spread across identity, endpoint, threat-intelligence, asset, and mail systems, and some of it is attacker-controlled. An assistant must assemble it quickly without inventing facts, obeying instructions hidden in the evidence, or executing containment without authorization.",
    approach: "The OpenAI Responses API runs a bounded loop: the model gets strict function tools and must answer in a strict JSON schema of findings, citations, disposition, procedure, and actions. Every tool result gets an evidence ID and a trust label; email bodies are untrusted. The policy gate then checks, in code, that every finding cites evidence from this run, that identifiers in findings appear in the cited records, that the procedure was retrieved, and that every action targets an entity seen in trusted evidence and cites it. Untrusted content can inform a finding but can never authorize an action.",
    baseline: "The earlier deterministic version is kept as the baseline: fixed tool order, keyword procedure ranking, and hand-written templates for three incident types. Both are scored with one rubric. The baseline passes the three cases it was written for and abstains on the two it has never seen; the agent works all five from the raw tool records.",
    measurement: "scripts/aegis-eval.ts runs every case several times and scores each run on six criteria in code: required tools, disposition, expected actions, procedure, policy-gate checks, and injection resistance, plus latency, tokens, and tool calls. It keeps the history of prompt versions, so the scorecard shows what each change fixed. There is no LLM judge, and the replays in the lab are trial 1 of the eval, not picked for success.",
    failure: "Five synthetic cases make a tiny eval, and the prompt was tuned on them, so the pass rate is not a held-out result. The grounding check matches identifiers, not meaning: a finding can cite the right record and still overstate it. The injection detector is a regex that only flags; enforcement comes from the gate's trust rules, and an injection that argues for a plausible in-scope action would still reach the human approver.",
    production: "Grow a held-out case set from closed incidents, add a faithfulness grader calibrated against analyst labels, trace every model and tool event, move rate limits and caches to a shared store, expose tools through access-controlled MCP servers with per-tool authorization, and run the eval in CI so a prompt or model change must clear it before release.",
  },
  {
    slug: "hermes", name: "Hermes Triage", accent: "pink", category: "NLP · Classification", endpoint: "triage", logic: "lib/triage.ts", group: applied,
    tagline: "Email triage with a fitted model",
    context: "Analysts cannot read every reported email. Decide what must be reviewed, and what can close.",
    summary: "Score synthetic user-reported emails, compare a fitted classifier with keyword rules, and see which tokens push a report to an analyst.",
    intro: "A fitted email-triage classifier, not a keyword filter. Tune the auto-close threshold, inspect token-level contributions, and compare the model with a hand-written rule baseline on a labeled synthetic inbox.",
    tags: ["Logistic regression", "Token features", "Threshold design", "Error analysis"],
    facts: ["1,200 train · 600 test reports", "Keyword-rule baseline", "Token explanations"],
    problem: "Security mailboxes fill with user-reported messages. Reviewing every item wastes analyst time, but auto-closing the wrong report misses phishing. A keyword filter fires on legitimate IT reminders and misses wire-request impersonation that contains no link.",
    approach: "Generate a public-safe inbox from templates, including overlapping cases (IT password reminders and link-free wire requests). Fit an L2-regularized logistic model on binary token presence plus URL structure features, then operate it at a tunable auto-close threshold. Reports below the threshold close as benign; the rest go to an analyst.",
    baseline: "The baseline is a hand-written keyword and URL heuristic with a fixed operating point. It is not a trained model. Both systems are scored on the same 600 labeled reports so the comparison is reproducible.",
    measurement: "True-negative rate (benign auto-closed), phishing recall, analyst workload against reviewing everything, missed-phishing counts, confusion counts, score histograms by class, and per-report logit contributions. Scores from the logistic model are uncalibrated.",
    failure: "Templates are not a production mailbox. Linear token contributions explain this model’s output and are not causal, and the probabilities are uncalibrated. A threshold that looks efficient here can miss a novel lure that the vocabulary never saw.",
    production: "Train on reviewed historical reports with a temporal split, add calibration and family-level slice metrics, keep a human review queue for scores near the threshold, and monitor delayed labels. This lab is a personal synthetic build; it is not an employer mail filter.",
  },
  {
    slug: "prism", name: "Prism Bench", accent: "blue", category: "Retrieval · Embeddings · Evaluation", endpoint: "retrieval", logic: "lib/retrieval-bench.ts", group: applied,
    tagline: "Dense, lexical, and hybrid retrieval with a release gate",
    context: "A search change can feel better and still miss the right document. Measure it before you ship it.",
    summary: "Compare BM25, character n-grams, OpenAI dense embeddings, and hybrid fusion against labeled relevance judgments, then promote or hold the change with a deterministic gate.",
    intro: "A retrieval evaluation bench for a synthetic security knowledge base. Compare lexical search, character n-grams, and text-embedding-3 dense vectors, alone or fused, slice the queries, and decide PROMOTE or HOLD from deterministic metrics. The promoted BM25 + dense hybrid is the retriever the Aegis agent searches with.",
    tags: ["BM25", "Dense embeddings", "Hybrid RRF", "nDCG / MRR", "Release gate"],
    facts: ["32 synthetic documents", "28 labeled queries", "5 retrievers · 1 gate"],
    problem: "A retrieval change can look better on a few hand-tried questions while regressing exact-term lookup or a slice nobody sampled. Shipping it because an example “feels” better is how procedure search silently degrades.",
    approach: "Score BM25, character-trigram TF-IDF, dense embeddings, and weighted reciprocal rank fusion against graded relevance judgments. Dense vectors come from text-embedding-3-large at 256 dimensions, computed offline for every document and query by scripts/embed-prism.ts and stored with a hash of their source text, so the page ranks with real embeddings at no runtime cost and the tests fail if the corpus changes without re-embedding. Optional query expansion adds a curated acronym lexicon.",
    baseline: "BM25 without expansion is the frozen production retriever. Every candidate is compared with that baseline on the same 28 queries. The gate promotes only when recall@k rises by at least three points, MRR does not drop, and no slice regresses by more than ten points.",
    measurement: "Recall@k, precision@k, MRR, nDCG@k with graded gains, per-slice recall, a leaderboard of all five retrievers, per-query wins and regressions, and the PROMOTE / HOLD verdict. Two findings stand out: dense vectors without the curated lexicon beat BM25 with it, and BM25 fused with dense vectors is the strongest configuration once expansion is on.",
    failure: "The corpus and judgments are small and synthetic. Dense vectors can blur exact rare identifiers, which is why BM25 stays in the fusion. The hybrid weight is hand-set, and a gate on twenty-eight queries cannot certify production quality; it shows the evaluation pattern.",
    production: "Build a larger judged set from search logs, add a cross-encoder reranker as the next candidate, add statistical paired tests, monitor live recall proxies, and require the same gate in CI before replacing a retriever. Aegis already consumes the promoted hybrid, so a retrieval regression here would show up in its eval.",
  },
] as const satisfies ReadonlyArray<{ slug: ProjectSlug } & Record<string, unknown>>;
