export type ProjectSlug = "atlas" | "sentinel" | "aegis" | "hermes" | "prism";

const platform = "Security intelligence platform";
const applied = "Applied ML & evaluation";

export const projects = [
  {
    slug: "atlas", name: "Atlas Graph", accent: "cyan", category: "Knowledge graph · Data engineering", endpoint: "graph", logic: "lib/platform.ts", group: platform,
    tagline: "Trusted entities and attack paths",
    context: "Security tools disagree about the same laptop. Trace every path to critical data, then remove one.",
    summary: "Resolve fragmented security records, calculate attack paths, and test which remediation removes the most risk.",
    intro: "Five fragmented security sources become one traceable graph. Explore every path from an external entry point to critical data, then test which control removes the most risk.",
    tags: ["Graph traversal", "Entity resolution", "Lineage", "What-if analysis"],
    facts: ["5 synthetic sources", "Attack-path search", "What-if remediation"],
    problem: "Security tools describe the same users, devices, services, and findings with different identifiers. Without trustworthy identity and relationships, downstream analytics produce duplicate alerts and misleading attack paths.",
    approach: "Compare source records field by field to link them into canonical entities with lineage, build a directed security graph, and enumerate every path from an exposed entry point to each critical data store. Every edge carries a relationship, an assumed likelihood, and the control that would remove it.",
    baseline: "The baseline graph uses exact identifiers and all observed edges. The enhanced pipeline links noisy records with weighted field comparisons, routes borderline pairs to review, and preserves the evidence behind each canonical entity.",
    measurement: "The live API reports reachable critical paths, the top path score, paths removed by each remediation, source coverage, and field-level match evidence. Path score is the product of edge likelihoods: a heuristic for ranking, not a probability of compromise.",
    failure: "Missing telemetry can hide edges, stale access data can create paths that no longer exist, and correlated edge assumptions make multiplicative scores optimistic. Match weights are hand-set here and must be learned and calibrated on reviewed pairs before production use.",
    production: "Process source snapshots with Spark, store the versioned graph in a graph database, learn entity-resolution weights from reviewed pairs, enforce field-level lineage, and validate proposed attack paths with asset owners before driving remediation.",
  },
  {
    slug: "sentinel", name: "Sentinel ModelOps", accent: "lime", category: "Machine learning · MLOps", endpoint: "monitor", logic: "lib/platform.ts", group: platform,
    tagline: "Fitted classifier, drift, and explanations",
    context: "A model can look accurate until live traffic shifts. Compare it with a simpler baseline.",
    summary: "Compare, explain, and stress-test a fitted intrusion classifier under population drift and different decision thresholds.",
    intro: "A fitted intrusion classifier, not a hand-written score. Compare the champion against its baseline, tune the operating threshold, introduce drift, and explain an individual prediction.",
    tags: ["Logistic regression", "Champion vs baseline", "PSI drift", "Local explanations"],
    facts: ["1,400 train · 600 test rows", "Champion vs baseline", "Drift & explanations"],
    problem: "A classifier can look strong at a default threshold while producing unacceptable false positives, failing on shifted traffic, or hiding which inputs drive individual decisions.",
    approach: "Fit two L2-regularized logistic models on a reproducible public-safe benchmark inspired by the UNSW-NB15 feature domain. Compare a two-feature baseline with a six-feature champion, then rescore a fixed test population under controlled covariate shift.",
    baseline: "The baseline is trained with two traffic features; the champion uses all six. Both are evaluated on the same 600 labeled samples, with the same threshold and drift controls, so the comparison is reproducible.",
    measurement: "Precision, recall, F1, false-positive rate, confusion counts, PSI, score distributions, fitted weights, and per-example logit contributions are calculated by the live endpoint. The source rows are generated and synthetic; results are not claims about the official UNSW-NB15 benchmark.",
    failure: "Synthetic features simplify real network behavior, PSI is sensitive to binning, and covariate drift does not necessarily imply quality loss. Linear contributions explain this model's output; they are not causal effects.",
    production: "Train on licensed source data with a temporal split, add calibration and attack-family slice metrics, log artifacts and data versions in MLflow, monitor delayed labels, and define champion–challenger rollback criteria.",
  },
  {
    slug: "aegis", name: "Aegis Investigator", accent: "violet", category: "Agentic workflow · Retrieval · Guardrails", endpoint: "agent", logic: "lib/platform.ts", group: platform,
    tagline: "Tool-using investigation with approval",
    context: "Incident evidence is spread across four systems. Assemble it, cite it, and stop before containment.",
    summary: "A deterministic investigation workflow that calls four security tools, retrieves the matching procedure, cites every statement, and pauses before containment.",
    intro: "A bounded, deterministic investigation workflow. It calls four read-only tools, retrieves the relevant procedure, writes a cited conclusion, runs rule-based checks on its own output, and stops before containment until a human approves.",
    tags: ["Typed tool calls", "Procedure retrieval", "Cited evidence", "Approval policy"],
    facts: ["4 typed tools", "Cited evidence", "Human approval gate"],
    problem: "Incident evidence is spread across identity, endpoint, threat-intelligence, asset, and procedure systems. An assistant must assemble it quickly without inventing facts or executing containment without authorization.",
    approach: "A typed state machine plans four read-only tool calls, validates their outputs, scores procedures by keyword and incident context, composes a cited conclusion from the returned records, runs deterministic checks, and stops at a human approval gate before any synthetic action. If any evidence or procedure check fails, the gate refuses approval.",
    baseline: "The earlier portfolio demo used BM25 and extractive answers only. This version adds tool orchestration, graph context, incident-aware procedure ranking, structured state, rule-based run checks, and an explicit action policy.",
    measurement: "Every run exposes tool inputs and outputs, procedure ranking, citations, latency, five deterministic checks, and approval state. The checks are rule-based assertions, not LLM evaluation, and the public runtime makes no model calls.",
    failure: "The tool registry and cases are intentionally bounded. A deterministic planner cannot handle arbitrary incidents, and rule checks verify structure (citations resolve, the right procedure, approval gating), not whether a conclusion is correct. A model-driven planner would add nondeterminism, prompt-injection risk, and cost.",
    production: "Connect an approved model for structured planning and grounded synthesis, expose access-controlled MCP tools, trace model and tool events, evaluate against ground-truth cases alongside these rule checks, add adversarial tests, enforce per-tool authorization, and compare quality against this deterministic baseline.",
  },
  {
    slug: "hermes", name: "Hermes Triage", accent: "pink", category: "NLP · Classification", endpoint: "triage", logic: "lib/triage.ts", group: applied,
    tagline: "Email triage with a fitted model",
    context: "Analysts cannot read every reported email. Decide what must be reviewed, and what can close.",
    summary: "Score synthetic user-reported emails, compare a fitted classifier with keyword rules, and see which tokens push a report to an analyst.",
    intro: "A fitted email-triage classifier, not a keyword filter. Tune the auto-close threshold, inspect token-level contributions, and compare the model with a hand-written rule baseline on a labeled synthetic inbox.",
    tags: ["Logistic regression", "Token features", "Threshold design", "Error analysis"],
    facts: ["1,200 train · 600 test reports", "Keyword-rule baseline", "Token explanations"],
    problem: "Security mailboxes fill with user-reported messages. Reviewing every item wastes analyst time, but auto-closing the wrong report misses phishing. A keyword filter fires on legitimate IT reminders and misses wire-request impersonation that contains no link.",
    approach: "Generate a public-safe inbox from templates, including overlapping cases (IT password reminders and link-free wire requests). Fit an L2-regularized logistic model on binary token presence plus URL structure features, then operate it at a tunable auto-close threshold. Reports below the threshold close as benign; the rest go to an analyst.",
    baseline: "The baseline is a hand-written keyword and URL heuristic with a fixed operating point. It is not a trained model. Both systems are scored on the same 600 labeled reports so the comparison is reproducible.",
    measurement: "True-negative rate (benign auto-closed), phishing recall, analyst workload against reviewing everything, missed-phishing counts, confusion counts, score histograms by class, and per-report logit contributions. Scores from the logistic model are uncalibrated.",
    failure: "Templates are not a production mailbox. Linear token contributions explain this model’s output and are not causal, and the probabilities are uncalibrated. A threshold that looks efficient here can miss a novel lure that the vocabulary never saw.",
    production: "Train on reviewed historical reports with a temporal split, add calibration and family-level slice metrics, keep a human review queue for scores near the threshold, and monitor delayed labels. This lab is a personal synthetic build; it is not an employer mail filter.",
  },
  {
    slug: "prism", name: "Prism Bench", accent: "blue", category: "Retrieval · Evaluation", endpoint: "retrieval", logic: "lib/retrieval-bench.ts", group: applied,
    tagline: "Retrieval evaluation with a release gate",
    context: "A search change can feel better and still miss the right document. Measure it before you ship it.",
    summary: "Compare BM25, character n-gram vectors, and hybrid fusion against labeled relevance judgments, then accept or hold the change with a deterministic gate.",
    intro: "A retrieval evaluation bench for a synthetic security knowledge base. Compare lexical search with character n-gram vectors and hybrid fusion, slice the queries, and decide PROMOTE or HOLD from deterministic metrics — no LLM judge.",
    tags: ["BM25", "Character n-grams", "nDCG / MRR", "Release gate"],
    facts: ["30 synthetic documents", "28 labeled queries", "Deterministic gate"],
    problem: "A retrieval change can look better on a few hand-tried questions while regressing exact-term lookup or a slice nobody sampled. Shipping it because an example “feels” better is how procedure search silently degrades.",
    approach: "Score BM25, character-trigram TF-IDF vectors, and weighted reciprocal rank fusion against graded relevance judgments. Optional query expansion adds a curated acronym and synonym lexicon. Metrics are computed at a chosen k and broken out by query slice. Character n-grams are a lexical vector baseline, not neural embeddings.",
    baseline: "BM25 without expansion is the frozen production retriever. Every candidate is compared with that baseline on the same 28 queries. The gate promotes only when recall@k rises by at least three points, MRR does not drop, and no slice regresses by more than ten points.",
    measurement: "Recall@k, precision@k, MRR, nDCG@k with graded gains, per-slice recall, per-query wins and regressions, and the PROMOTE / HOLD verdict with the failed rules. These are deterministic IR metrics, not LLM evaluation.",
    failure: "The corpus and judgments are small and synthetic. Character n-grams are not semantic embeddings, so paraphrase coverage is limited even with expansion. A gate on twenty-eight queries cannot certify production quality; it only shows the evaluation pattern.",
    production: "Build a larger judged set from search logs, add statistical paired tests, monitor live recall proxies, and require the same gate in CI before replacing keyword retrieval. This bench is how a change to Aegis-style procedure search would be proven before adoption, not a live employer evaluator.",
  },
] as const satisfies ReadonlyArray<{ slug: ProjectSlug } & Record<string, unknown>>;
